package org.dp.entity;

public class JbrCategoryWithBLOBs extends JbrCategory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_category.arrchildid
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String arrchildid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_category.description
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_category.setting
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String setting;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_category.arrchildid
	 * @return  the value of jbr_category.arrchildid
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getArrchildid() {
		return arrchildid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_category.arrchildid
	 * @param arrchildid  the value for jbr_category.arrchildid
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setArrchildid(String arrchildid) {
		this.arrchildid = arrchildid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_category.description
	 * @return  the value of jbr_category.description
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_category.description
	 * @param description  the value for jbr_category.description
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_category.setting
	 * @return  the value of jbr_category.setting
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getSetting() {
		return setting;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_category.setting
	 * @param setting  the value for jbr_category.setting
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setSetting(String setting) {
		this.setting = setting;
	}
}