package org.dp.entity;

public class JbrCategory {

//	@Override
//	public String toString() {
//		// TODO Auto-generated method stub
//		 return "JbrCategory[" +
//         "catid=" + catid +
//         ",parentid=" + parentid +
//         ",catname="+ catname +
//         "]";
//	}
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_category.catid
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Short catid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_category.module
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String module;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_category.type
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Boolean type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_category.modelid
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Short modelid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_category.domain
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String domain;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_category.parentid
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Short parentid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_category.arrparentid
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String arrparentid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_category.child
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Boolean child;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_category.catname
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String catname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_category.image
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String image;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_category.parentdir
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String parentdir;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_category.catdir
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String catdir;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_category.url
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_category.hits
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Integer hits;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_category.listorder
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Short listorder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_category.ismenu
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Boolean ismenu;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_category.sethtml
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Boolean sethtml;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_category.letter
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String letter;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_category.catid
	 * @return  the value of jbr_category.catid
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Short getCatid() {
		return catid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_category.catid
	 * @param catid  the value for jbr_category.catid
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setCatid(Short catid) {
		this.catid = catid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_category.module
	 * @return  the value of jbr_category.module
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getModule() {
		return module;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_category.module
	 * @param module  the value for jbr_category.module
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setModule(String module) {
		this.module = module;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_category.type
	 * @return  the value of jbr_category.type
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Boolean getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_category.type
	 * @param type  the value for jbr_category.type
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setType(Boolean type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_category.modelid
	 * @return  the value of jbr_category.modelid
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Short getModelid() {
		return modelid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_category.modelid
	 * @param modelid  the value for jbr_category.modelid
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setModelid(Short modelid) {
		this.modelid = modelid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_category.domain
	 * @return  the value of jbr_category.domain
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getDomain() {
		return domain;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_category.domain
	 * @param domain  the value for jbr_category.domain
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setDomain(String domain) {
		this.domain = domain;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_category.parentid
	 * @return  the value of jbr_category.parentid
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Short getParentid() {
		return parentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_category.parentid
	 * @param parentid  the value for jbr_category.parentid
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setParentid(Short parentid) {
		this.parentid = parentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_category.arrparentid
	 * @return  the value of jbr_category.arrparentid
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getArrparentid() {
		return arrparentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_category.arrparentid
	 * @param arrparentid  the value for jbr_category.arrparentid
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setArrparentid(String arrparentid) {
		this.arrparentid = arrparentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_category.child
	 * @return  the value of jbr_category.child
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Boolean getChild() {
		return child;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_category.child
	 * @param child  the value for jbr_category.child
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setChild(Boolean child) {
		this.child = child;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_category.catname
	 * @return  the value of jbr_category.catname
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getCatname() {
		return catname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_category.catname
	 * @param catname  the value for jbr_category.catname
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setCatname(String catname) {
		this.catname = catname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_category.image
	 * @return  the value of jbr_category.image
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getImage() {
		return image;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_category.image
	 * @param image  the value for jbr_category.image
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setImage(String image) {
		this.image = image;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_category.parentdir
	 * @return  the value of jbr_category.parentdir
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getParentdir() {
		return parentdir;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_category.parentdir
	 * @param parentdir  the value for jbr_category.parentdir
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setParentdir(String parentdir) {
		this.parentdir = parentdir;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_category.catdir
	 * @return  the value of jbr_category.catdir
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getCatdir() {
		return catdir;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_category.catdir
	 * @param catdir  the value for jbr_category.catdir
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setCatdir(String catdir) {
		this.catdir = catdir;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_category.url
	 * @return  the value of jbr_category.url
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_category.url
	 * @param url  the value for jbr_category.url
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_category.hits
	 * @return  the value of jbr_category.hits
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Integer getHits() {
		return hits;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_category.hits
	 * @param hits  the value for jbr_category.hits
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setHits(Integer hits) {
		this.hits = hits;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_category.listorder
	 * @return  the value of jbr_category.listorder
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Short getListorder() {
		return listorder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_category.listorder
	 * @param listorder  the value for jbr_category.listorder
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setListorder(Short listorder) {
		this.listorder = listorder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_category.ismenu
	 * @return  the value of jbr_category.ismenu
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Boolean getIsmenu() {
		return ismenu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_category.ismenu
	 * @param ismenu  the value for jbr_category.ismenu
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setIsmenu(Boolean ismenu) {
		this.ismenu = ismenu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_category.sethtml
	 * @return  the value of jbr_category.sethtml
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Boolean getSethtml() {
		return sethtml;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_category.sethtml
	 * @param sethtml  the value for jbr_category.sethtml
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setSethtml(Boolean sethtml) {
		this.sethtml = sethtml;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_category.letter
	 * @return  the value of jbr_category.letter
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getLetter() {
		return letter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_category.letter
	 * @param letter  the value for jbr_category.letter
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setLetter(String letter) {
		this.letter = letter;
	}
}