package org.dp.entity;

public class JbrJubaoData {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_jubao_data.id
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_jubao_data.paginationtype
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Boolean paginationtype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_jubao_data.maxcharperpage
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Integer maxcharperpage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_jubao_data.paytype
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Boolean paytype;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_jubao_data.id
	 * @return  the value of jbr_jubao_data.id
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_jubao_data.id
	 * @param id  the value for jbr_jubao_data.id
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_jubao_data.paginationtype
	 * @return  the value of jbr_jubao_data.paginationtype
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Boolean getPaginationtype() {
		return paginationtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_jubao_data.paginationtype
	 * @param paginationtype  the value for jbr_jubao_data.paginationtype
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setPaginationtype(Boolean paginationtype) {
		this.paginationtype = paginationtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_jubao_data.maxcharperpage
	 * @return  the value of jbr_jubao_data.maxcharperpage
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Integer getMaxcharperpage() {
		return maxcharperpage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_jubao_data.maxcharperpage
	 * @param maxcharperpage  the value for jbr_jubao_data.maxcharperpage
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setMaxcharperpage(Integer maxcharperpage) {
		this.maxcharperpage = maxcharperpage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_jubao_data.paytype
	 * @return  the value of jbr_jubao_data.paytype
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Boolean getPaytype() {
		return paytype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_jubao_data.paytype
	 * @param paytype  the value for jbr_jubao_data.paytype
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setPaytype(Boolean paytype) {
		this.paytype = paytype;
	}
}