package org.dp.entity;

public class JbrJubao {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_jubao.id
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_jubao.catid
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Short catid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_jubao.typeid
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Short typeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_jubao.title
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_jubao.style
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String style;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_jubao.thumb
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String thumb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_jubao.description
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_jubao.posid
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Boolean posid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_jubao.url
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_jubao.listorder
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Byte listorder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_jubao.status
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_jubao.sysadd
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Boolean sysadd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_jubao.islink
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Boolean islink;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_jubao.username
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_jubao.inputtime
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Integer inputtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_jubao.updatetime
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Integer updatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_jubao.views
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Integer views;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_jubao.yesterdayviews
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Integer yesterdayviews;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_jubao.dayviews
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Integer dayviews;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_jubao.weekviews
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Integer weekviews;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_jubao.monthviews
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Integer monthviews;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_jubao.viewsupdatetime
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Integer viewsupdatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_jubao.id
	 * @return  the value of jbr_jubao.id
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_jubao.id
	 * @param id  the value for jbr_jubao.id
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_jubao.catid
	 * @return  the value of jbr_jubao.catid
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Short getCatid() {
		return catid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_jubao.catid
	 * @param catid  the value for jbr_jubao.catid
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setCatid(Short catid) {
		this.catid = catid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_jubao.typeid
	 * @return  the value of jbr_jubao.typeid
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Short getTypeid() {
		return typeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_jubao.typeid
	 * @param typeid  the value for jbr_jubao.typeid
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setTypeid(Short typeid) {
		this.typeid = typeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_jubao.title
	 * @return  the value of jbr_jubao.title
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_jubao.title
	 * @param title  the value for jbr_jubao.title
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_jubao.style
	 * @return  the value of jbr_jubao.style
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getStyle() {
		return style;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_jubao.style
	 * @param style  the value for jbr_jubao.style
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setStyle(String style) {
		this.style = style;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_jubao.thumb
	 * @return  the value of jbr_jubao.thumb
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getThumb() {
		return thumb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_jubao.thumb
	 * @param thumb  the value for jbr_jubao.thumb
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setThumb(String thumb) {
		this.thumb = thumb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_jubao.description
	 * @return  the value of jbr_jubao.description
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_jubao.description
	 * @param description  the value for jbr_jubao.description
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_jubao.posid
	 * @return  the value of jbr_jubao.posid
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Boolean getPosid() {
		return posid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_jubao.posid
	 * @param posid  the value for jbr_jubao.posid
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setPosid(Boolean posid) {
		this.posid = posid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_jubao.url
	 * @return  the value of jbr_jubao.url
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_jubao.url
	 * @param url  the value for jbr_jubao.url
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_jubao.listorder
	 * @return  the value of jbr_jubao.listorder
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Byte getListorder() {
		return listorder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_jubao.listorder
	 * @param listorder  the value for jbr_jubao.listorder
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setListorder(Byte listorder) {
		this.listorder = listorder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_jubao.status
	 * @return  the value of jbr_jubao.status
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_jubao.status
	 * @param status  the value for jbr_jubao.status
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_jubao.sysadd
	 * @return  the value of jbr_jubao.sysadd
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Boolean getSysadd() {
		return sysadd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_jubao.sysadd
	 * @param sysadd  the value for jbr_jubao.sysadd
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setSysadd(Boolean sysadd) {
		this.sysadd = sysadd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_jubao.islink
	 * @return  the value of jbr_jubao.islink
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Boolean getIslink() {
		return islink;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_jubao.islink
	 * @param islink  the value for jbr_jubao.islink
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setIslink(Boolean islink) {
		this.islink = islink;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_jubao.username
	 * @return  the value of jbr_jubao.username
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_jubao.username
	 * @param username  the value for jbr_jubao.username
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_jubao.inputtime
	 * @return  the value of jbr_jubao.inputtime
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Integer getInputtime() {
		return inputtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_jubao.inputtime
	 * @param inputtime  the value for jbr_jubao.inputtime
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setInputtime(Integer inputtime) {
		this.inputtime = inputtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_jubao.updatetime
	 * @return  the value of jbr_jubao.updatetime
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Integer getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_jubao.updatetime
	 * @param updatetime  the value for jbr_jubao.updatetime
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setUpdatetime(Integer updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_jubao.views
	 * @return  the value of jbr_jubao.views
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Integer getViews() {
		return views;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_jubao.views
	 * @param views  the value for jbr_jubao.views
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setViews(Integer views) {
		this.views = views;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_jubao.yesterdayviews
	 * @return  the value of jbr_jubao.yesterdayviews
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Integer getYesterdayviews() {
		return yesterdayviews;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_jubao.yesterdayviews
	 * @param yesterdayviews  the value for jbr_jubao.yesterdayviews
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setYesterdayviews(Integer yesterdayviews) {
		this.yesterdayviews = yesterdayviews;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_jubao.dayviews
	 * @return  the value of jbr_jubao.dayviews
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Integer getDayviews() {
		return dayviews;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_jubao.dayviews
	 * @param dayviews  the value for jbr_jubao.dayviews
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setDayviews(Integer dayviews) {
		this.dayviews = dayviews;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_jubao.weekviews
	 * @return  the value of jbr_jubao.weekviews
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Integer getWeekviews() {
		return weekviews;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_jubao.weekviews
	 * @param weekviews  the value for jbr_jubao.weekviews
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setWeekviews(Integer weekviews) {
		this.weekviews = weekviews;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_jubao.monthviews
	 * @return  the value of jbr_jubao.monthviews
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Integer getMonthviews() {
		return monthviews;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_jubao.monthviews
	 * @param monthviews  the value for jbr_jubao.monthviews
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setMonthviews(Integer monthviews) {
		this.monthviews = monthviews;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_jubao.viewsupdatetime
	 * @return  the value of jbr_jubao.viewsupdatetime
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Integer getViewsupdatetime() {
		return viewsupdatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_jubao.viewsupdatetime
	 * @param viewsupdatetime  the value for jbr_jubao.viewsupdatetime
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setViewsupdatetime(Integer viewsupdatetime) {
		this.viewsupdatetime = viewsupdatetime;
	}
}