package org.dp.entity;

public class JbrLawData {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_law_data.id
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_law_data.paginationtype
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Boolean paginationtype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_law_data.maxcharperpage
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Integer maxcharperpage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_law_data.paytype
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Boolean paytype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_law_data.relation
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String relation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_law_data.content
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_law_data.id
	 * @return  the value of jbr_law_data.id
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_law_data.id
	 * @param id  the value for jbr_law_data.id
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_law_data.paginationtype
	 * @return  the value of jbr_law_data.paginationtype
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Boolean getPaginationtype() {
		return paginationtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_law_data.paginationtype
	 * @param paginationtype  the value for jbr_law_data.paginationtype
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setPaginationtype(Boolean paginationtype) {
		this.paginationtype = paginationtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_law_data.maxcharperpage
	 * @return  the value of jbr_law_data.maxcharperpage
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Integer getMaxcharperpage() {
		return maxcharperpage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_law_data.maxcharperpage
	 * @param maxcharperpage  the value for jbr_law_data.maxcharperpage
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setMaxcharperpage(Integer maxcharperpage) {
		this.maxcharperpage = maxcharperpage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_law_data.paytype
	 * @return  the value of jbr_law_data.paytype
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Boolean getPaytype() {
		return paytype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_law_data.paytype
	 * @param paytype  the value for jbr_law_data.paytype
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setPaytype(Boolean paytype) {
		this.paytype = paytype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_law_data.relation
	 * @return  the value of jbr_law_data.relation
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getRelation() {
		return relation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_law_data.relation
	 * @param relation  the value for jbr_law_data.relation
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setRelation(String relation) {
		this.relation = relation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_law_data.content
	 * @return  the value of jbr_law_data.content
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_law_data.content
	 * @param content  the value for jbr_law_data.content
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setContent(String content) {
		this.content = content;
	}
}