package org.dp.entity;

public class JbrReport {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_report.id
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_report.user_name
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String user_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_report.user_idcard
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String user_idcard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_report.user_phone
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String user_phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_report.user_zz
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String user_zz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_report.user_dizhi
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String user_dizhi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_report.user_jb
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String user_jb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_report.report_name
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String report_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_report.report_dw
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String report_dw;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_report.report_zw
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String report_zw;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_report.report_jb
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String report_jb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_report.title
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_report.question1
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Integer question1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_report.question2
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Integer question2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_report.files
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String files;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_report.datetime
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String datetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_report.status
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jbr_report.content
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	private String content;

	private String filename;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_report.id
	 * @return  the value of jbr_report.id
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_report.id
	 * @param id  the value for jbr_report.id
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_report.user_name
	 * @return  the value of jbr_report.user_name
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getUser_name() {
		return user_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_report.user_name
	 * @param user_name  the value for jbr_report.user_name
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setUser_name(String user_name) {
		this.user_name = user_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_report.user_idcard
	 * @return  the value of jbr_report.user_idcard
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getUser_idcard() {
		return user_idcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_report.user_idcard
	 * @param user_idcard  the value for jbr_report.user_idcard
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setUser_idcard(String user_idcard) {
		this.user_idcard = user_idcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_report.user_phone
	 * @return  the value of jbr_report.user_phone
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getUser_phone() {
		return user_phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_report.user_phone
	 * @param user_phone  the value for jbr_report.user_phone
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setUser_phone(String user_phone) {
		this.user_phone = user_phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_report.user_zz
	 * @return  the value of jbr_report.user_zz
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getUser_zz() {
		return user_zz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_report.user_zz
	 * @param user_zz  the value for jbr_report.user_zz
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setUser_zz(String user_zz) {
		this.user_zz = user_zz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_report.user_dizhi
	 * @return  the value of jbr_report.user_dizhi
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getUser_dizhi() {
		return user_dizhi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_report.user_dizhi
	 * @param user_dizhi  the value for jbr_report.user_dizhi
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setUser_dizhi(String user_dizhi) {
		this.user_dizhi = user_dizhi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_report.user_jb
	 * @return  the value of jbr_report.user_jb
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getUser_jb() {
		return user_jb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_report.user_jb
	 * @param user_jb  the value for jbr_report.user_jb
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setUser_jb(String user_jb) {
		this.user_jb = user_jb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_report.report_name
	 * @return  the value of jbr_report.report_name
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getReport_name() {
		return report_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_report.report_name
	 * @param report_name  the value for jbr_report.report_name
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setReport_name(String report_name) {
		this.report_name = report_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_report.report_dw
	 * @return  the value of jbr_report.report_dw
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getReport_dw() {
		return report_dw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_report.report_dw
	 * @param report_dw  the value for jbr_report.report_dw
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setReport_dw(String report_dw) {
		this.report_dw = report_dw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_report.report_zw
	 * @return  the value of jbr_report.report_zw
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getReport_zw() {
		return report_zw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_report.report_zw
	 * @param report_zw  the value for jbr_report.report_zw
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setReport_zw(String report_zw) {
		this.report_zw = report_zw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_report.report_jb
	 * @return  the value of jbr_report.report_jb
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getReport_jb() {
		return report_jb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_report.report_jb
	 * @param report_jb  the value for jbr_report.report_jb
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setReport_jb(String report_jb) {
		this.report_jb = report_jb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_report.title
	 * @return  the value of jbr_report.title
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_report.title
	 * @param title  the value for jbr_report.title
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_report.question1
	 * @return  the value of jbr_report.question1
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Integer getQuestion1() {
		return question1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_report.question1
	 * @param question1  the value for jbr_report.question1
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setQuestion1(Integer question1) {
		this.question1 = question1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_report.question2
	 * @return  the value of jbr_report.question2
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Integer getQuestion2() {
		return question2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_report.question2
	 * @param question2  the value for jbr_report.question2
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setQuestion2(Integer question2) {
		this.question2 = question2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_report.files
	 * @return  the value of jbr_report.files
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getFiles() {
		return files;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_report.files
	 * @param files  the value for jbr_report.files
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setFiles(String files) {
		this.files = files;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_report.datetime
	 * @return  the value of jbr_report.datetime
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getDatetime() {
		return datetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_report.datetime
	 * @param datetime  the value for jbr_report.datetime
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setDatetime(String datetime) {
		this.datetime = datetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_report.status
	 * @return  the value of jbr_report.status
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public Integer getStatus() {
		return status==null?0:status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_report.status
	 * @param status  the value for jbr_report.status
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jbr_report.content
	 * @return  the value of jbr_report.content
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jbr_report.content
	 * @param content  the value for jbr_report.content
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	public void setContent(String content) {
		this.content = content;
	}

	public String getFilename() {
		return filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}
}