package org.dp.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.dp.entity.JbrJubao;

public interface JbrJubaoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbr_jubao
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbr_jubao
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	int insert(JbrJubao record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbr_jubao
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	int insertSelective(JbrJubao record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbr_jubao
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	JbrJubao selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbr_jubao
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	int updateByPrimaryKeySelective(JbrJubao record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbr_jubao
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	int updateByPrimaryKey(JbrJubao record);
	
	List<JbrJubao> selectByCatid(@Param("catid")short catid);

}