package org.dp.dao;

import org.dp.entity.JbrJubaoData;

public interface JbrJubaoDataMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbr_jubao_data
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbr_jubao_data
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	int insert(JbrJubaoData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbr_jubao_data
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	int insertSelective(JbrJubaoData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbr_jubao_data
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	JbrJubaoData selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbr_jubao_data
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	int updateByPrimaryKeySelective(JbrJubaoData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbr_jubao_data
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	int updateByPrimaryKey(JbrJubaoData record);
}