package org.dp.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.dp.entity.JbrLaw;
import org.dp.service.page.PageParam;

public interface JbrLawMapper {


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbr_law
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbr_law
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	int insert(JbrLaw record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbr_law
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	int insertSelective(JbrLaw record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbr_law
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	JbrLaw selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbr_law
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	int updateByPrimaryKeySelective(JbrLaw record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbr_law
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	int updateByPrimaryKey(JbrLaw record);
	List<JbrLaw> selectPageAll(@Param("pageParam")PageParam pageParam);
	long getTotalNum();
}