package org.dp.dao;

import org.dp.entity.JbrLawData;

public interface JbrLawDataMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbr_law_data
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbr_law_data
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	int insert(JbrLawData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbr_law_data
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	int insertSelective(JbrLawData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbr_law_data
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	JbrLawData selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbr_law_data
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	int updateByPrimaryKeySelective(JbrLawData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbr_law_data
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(JbrLawData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbr_law_data
	 * @mbggenerated  Wed May 03 16:28:45 CST 2017
	 */
	int updateByPrimaryKey(JbrLawData record);
	
}